name: Bug report
description: Report a bug in alt:V Multiplayer
labels: ['Class: bug']

body:
  - type: textarea
    id: description
    attributes:
      label: Description of the problem
      description: Describe the exact problem.
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Describe how to reproduce the problem
      placeholder: A clear and concise list of steps on how to reproduce the problem or code to reproduce the problem.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: Describe the expected behaviour
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: 'Any other additional context you''d like to add'
      placeholder: Add any other context or screenshots about the problem here.
  - type: input
    id: os
    attributes:
      label: Operating system
      description: On what operating system is the issue present
      placeholder: E.g. Ubuntu 20.04
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: On what version is the issue present
      placeholder: e.g. dev/7.0-dev3
    validations:
      required: true
  - type: input
    id: crashdumpid
    attributes:
      label: Crashdump ID
      description: The crashdump id you received on a client crash
  - type: checkboxes
    attributes:
      label: Reproduction tested
      description: Make sure you can confirm this issue also exists on the newest dev version
      options:
      - label: I confirm that I have made sure that this issue is also present on the newest dev version
        required: true
