--- 
blank_issues_enabled: false
contact_links: 
  - 
    about: "Please ask and answer usage questions on Stack Overflow."
    name: "Question"
    url: "https://stackoverflow.com/questions/tagged/altv"
  - 
    about: "Alternatively, you can use the alt:V Official Discord."
    name: "Support channel"
    url: "https://discord.altv.mp/"
  - 
    about: "Please check the Troubleshooting before filing new issues."
    name: "alt:V Troubleshooting"
    url: "https://wiki.altv.mp/wiki/Tutorial:Troubleshoot_Client"
